#! /bin/bash
#
#   arg1  = rundir to be created. if already exist, no work is done. Needs to be a simple name, no / allowed
#   arg2+ = arguments to replace the template mcterm.par
#
#   Template parameter file 'mcterm.par' needs to exist here (or a symlink to one in models/*/mcterm.par)
#   Link to 'parfiles' needs to exists here as wel

if [ $# -lt 2 ]; then
    echo "Usage: $0 <RUNDIR> PAR1=VAL1 PAR2=VAL2 ..."
    echo "PAR's need to be valid parameter names from the mctherm.par file"
    exit 0
fi

run=../../src/ttsre
time=/usr/bin/time
par=mctherm.par
rundir=$1
shift

if [ -d $rundir ]; then
    echo $rundir exists, skipping work
    exit 0
fi

if [ ! -e $par ]; then
    echo "template $par does not exist here in $(pwd)"
    exit 0
fi

if [ ! -e parfiles ]; then
    echo "Warning: parfiles does not exist."
    exit 0
fi


echo run_hochunk3d $rundir $*
mkdir $rundir
cd $rundir
pedit ../$par -r -e $* > $par
$time $run > run.log 2>&1 

